version: '3'

services:
  db:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_EXPOSE_PORT:-55432}:5432'
  app:
    env_file: .env
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '${APP_EXPOSE_PORT:-58000}:8000'
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local
